name = "hono-app"
compatibility_date = "2023-12-01"
main = "src/index.ts"
minify = true

[env.dev.vars]
MY_VAR = "my-variable"
DEV_VAR = ""

[env.staging.vars]
MY_VAR = "my-variable-staging"

[env.production.vars]
MY_VAR = "my-variable-production"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
